[package]
name = "hello-rust"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["app", "bzlib-sys", "ffi", "generic", "httpie", "kv1", "leetcode", "queryer", "rgrep", "scrape_url", "shared", "solid", "thumbor"]
