[package]
name = "rgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
thiserror = "2.0.15"
